"""Post-retrieval report and two standard matplotlib figures; no scientific simulation."""
import os
os.environ.setdefault('MPLBACKEND','Agg');os.environ.setdefault('OPENBLAS_NUM_THREADS','1')
from common import *

def main():
 verify_manifest('SOURCE_SHA256SUMS');verify_manifest('RESULT_SHA256SUMS');assert read('LIVE_RESULT.json')['status']=='COMPLETE';assert read('AUDIT_CHECK.json')['status']=='PASS'
 import matplotlib.pyplot as plt
 estimates=read('ESTIMATES.json');diagnostics=read('DIAGNOSTICS.json');primary=read('VALIDATION_CHECK.json');groups=list(read('GROUP_TABLE.json'))
 fig,ax=plt.subplots(figsize=(9,8))
 for i,g in enumerate(groups):
  r=estimates[g+'|DELTA'];a,b=r['ci95'];color='#155e75' if r['classification']!='unresolved' else '#666666';ax.hlines(i,a*100,b*100,color=color);ax.plot(r['mean']*100,i,'o',color=color)
 ax.set_yticks(range(len(groups)),groups);ax.invert_yaxis();ax.axvline(0,color='black',lw=.8);ax.set_xlabel('DELTA (percentage points; pointwise exploratory 95% interval)');ax.set_title('Native interaction minus reshaped interaction');fig.tight_layout();fig.savefig(P/'conditional_delta.png',dpi=170);plt.close(fig)
 fig,axes=plt.subplots(1,3,figsize=(12,4));series=diagnostics['generations'];gens=[x['generation'] for x in series]
 for ax,key,title in zip(axes,('centroid_max_difference','covariance_max_difference','mean_absolute_performance_difference'),('Maximum centroid difference','Maximum covariance difference','Mean absolute performance difference')):
  ax.plot(gens,[x[key] for x in series],marker='.',color='#155e75');ax.set_xlabel('Generation');ax.set_title(title,fontsize=10);ax.set_yscale('symlog',linthresh=1e-12);ax.axvline(5,color='gray',lw=.6)
 fig.suptitle('Matched initial moments; subsequent differences are descriptive');fig.tight_layout();fig.savefig(P/'state_diagnostics.png',dpi=170);plt.close(fig)
 r=primary['primary_estimate'];lines=['# Population-shape intervention064','',f"Primary structured|ALL8|DELTA: {r['mean']:.8g}, 95% interval [{r['ci95'][0]:.8g}, {r['ci95'][1]:.8g}]. Classification: **{r['classification']}**; {primary['scientific_status']}.",'','The working prediction was negative. DELTA compares the native early-state-by-later-rule interaction with the reshaped interaction. G_MEAN is a separate performance companion. No outcome replaced the primary.','',f"Job: {read('LIVE_RESULT.json')['job_id']}. One allocation; 12,288 new paths and 12,288 stored controls. 24 paired history blocks, eight equally weighted existing families, 2,000 common bootstrap rows. No new training or replay of native controls.",'','## All conditional and pooled results','','All values below are normalized performance fractions. Intervals are pointwise exploratory, not simultaneous.','', '| Group | Metric | Mean | Lower | Upper | Classification |','|---|---|---:|---:|---:|---|']
 for key,v in estimates.items():
  group,metric=key.rsplit('|',1);lines.append(f"| {group} | {metric} | {v['mean']:.9g} | {v['ci95'][0]:.9g} | {v['ci95'][1]:.9g} | {v['classification']} |")
 lines+=['','## Initial checks and later divergence','',f"All {diagnostics['initial_moment_checks']} initial source states checked. Maximum errors: `{json.dumps(diagnostics['maximum_initial_errors'],sort_keys=True)}`.",'','Subsequent centroid/covariance changes are permitted; DIAGNOSTICS.json gives all generation5–25 summaries. Both native and reshaped arms are included above.','', '| Cell | Declining updates | Negative measurements | Negative endpoints |','|---|---:|---:|---:|']
 for c in diagnostics['declining_updates']:lines.append(f"| {c} | {diagnostics['declining_updates'][c]} | {diagnostics['negative_measurements'][c]} | {diagnostics['negative_endpoints'][c]} |")
 lines+=['','## Interpretation limits','','Reshaping preserves first two trait moments and initial quadratic mean loss, while changing population arrangement, potentially including tails, multimodality, duplicates and individual losses. It does not identify a unique higher-moment mediator. The finite transformed cloud is not an independent Gaussian sample. Matching is only at the intervention instant. Historical inputs and continuation randomness are reused. This is not independent training replication. An unresolved interval does not show equivalence or moment sufficiency; a positive primary contradicts the fixed negative prediction. ALL8 is the equally weighted existing panel, not a naturally sampled task distribution. No practical-benefit threshold or new scientific variant is inferred.','','## Evidence','','AUDIT_CHECK.json records executor-supplied separate arithmetic reconstruction of380estimates,6144initial invariants, and the prespecified128row raw block. Supervisor acceptance remains separate. ACCOUNTING.psv, MEMORY_TELEMETRY.jsonl and RUNTIME.json retain observed resource records. Source, inputs, results and delivery have separate manifests.','','![Conditional effects](conditional_delta.png)','','![State diagnostics](state_diagnostics.png)','']
 (P/'REPORT.md').write_text('\n'.join(lines));save('REPORT_GENERATION.json',dict(status='GENERATED_PENDING_VISUAL_INSPECTION',plots=['conditional_delta.png','state_diagnostics.png'],report='REPORT.md',package_bytes=package_bytes()));assert package_bytes()<=LIMIT
if __name__=='__main__':main()
